name: RUN TESTS CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: behave -f allure_behave.formatter:AllureFormatter -o allure-results --exclude="performance.feature" ./features

      - name: Generate Allure Report
        run: |
          # Install Allure CLI (if not already available)
          sudo apt-get update && sudo apt-get install -y openjdk-11-jre
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.zip
          unzip allure-commandline-2.24.1.zip
          export PATH=$PATH:$(pwd)/allure-2.24.1/bin
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_number }}
          path: allure-report