name: Behave CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: behave -f allure_behave.formatter:AllureFormatter -o allure-results --exclude="performance.feature" ./features

      - name: Generate Allure test report
        uses: andgineer/allure-report@v3.6
        id: allure-report
        if: always() 
        with:
          allure-results: allure-results
          website: gh-pages-dir
          reports-site-path: builds/tests

      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-html
          path: allure-report